version: '3'
services: 
  postgres: 
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: 'redis:latest'
  nginx: 
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes: 
      # if you look at the Dockerfile.dev for server you'll see we set a working directory of /app
      # this first item says to use whatever is under that working directory/node_modules in the container.
      - /app/node_modules
      # This next line then says anything other than what's under /app/node_modules should be based on what is on my computer under ./server.
      # This allows me to change code without it trying to find the node_modules stuff which is built inside the containe and not on my computer.
      - ./server:/app
    environment:
      - REDIS_HOST=redis   
      - REDIS_PORT=6379   
      - PGUSER=postgres 
      - PGHOST=postgres 
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password 
      - PGPORT=5432 
    depends_on:
      - postgres
      - redis
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis   
      - REDIS_PORT=6379 
    depends_on:
      - redis      
